.Preface

The ModSpec specifies a formal structure for standards documents but does not supply
specific content. This Part 2 specifies the optional UML Requirements Class. 

////
*OGC Declaration*
////

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. The Open Geospatial Consortium shall not be held responsible for identifying any or all such patent rights.

Recipients of this document are requested to submit, with their comments, notification of any relevant patent claims or other intellectual property rights of which they may be aware that might be infringed by any implementation of the standard set forth in this document, and to provide supporting documentation.

////
NOTE: Uncomment ISO section if necessary

*ISO Declaration*

ISO (the International Organization for Standardization) is a worldwide federation of national standards bodies (ISO member bodies). The work of preparing International Standards is normally carried out through ISO technical committees. Each member body interested in a subject for which a technical committee has been established has the right to be represented on that committee. International organizations, governmental and non-governmental, in liaison with ISO, also take part in the work. ISO collaborates closely with the International Electrotechnical Commission (IEC) on all matters of electrotechnical standardization.

International Standards are drafted in accordance with the rules given in the ISO/IEC Directives, Part 2.

The main task of technical committees is to prepare International Standards. Draft International Standards adopted by the technical committees are circulated to the member bodies for voting. Publication as an International Standard requires approval by at least 75 % of the member bodies casting a vote.

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. ISO shall not be held responsible for identifying any or all such patent rights.
////

[abstract]
== Abstract

This OGC member developed and approved document, referred to as the `ModSpec: Part 2 - UML`, defines an optional requirements class for UML

The ModSpec: Core Standard defines a model and related requirements 
and recommendations for writing and structuring modular standards documents. Further, this model is designed to enable 
consistent and verifiable testing of implementations of a standard that claim conformance. The ModSpec is a meta-standard: 
A standard specifying requirements for crafting and documenting modular and testable standards. 

The goals of using the ModSpec are:

- To define characteristics and a structure for the development of modular standards which will minimize the difficulty in writing testable standards while maximizing usability and interoperability.
- To ensure that a standard specifies requirements in a common and consistent manner and that these requirements are testable.

NOTE: Historically, this document has been known and abbreviated as the "ModSpec". For continuity and ease of understanding this document may also be referred to as the "OGC ModSpec".

Suggested additions, changes, and comments on this document are welcome and
encouraged. Such suggestions may be submitted by creating an issue in the GitHub 
repository for this document (https://github.com/opengeospatial/ogc-modspec).

== Security considerations

No security considerations have been made for this Standard.

== Submitters

All questions regarding this submission should be directed to the editor or the submitters:

|===
|*Name* |*Affiliation*
| Carl Reed | Carl Reed & Associates
| John Herring, PhD | Oracle |
|===

== Contributors

Additional contributors to this Standard include the following:

|===
|*Name* |*Organization*
| Carl Reed, PhD| Carl Reed
| Chuck Heazel | Heazeltech
| Jeff Yutzler | ImageMatters
|===

[.preface]
== Acknowledgements

The following OGC Members were key contributors to Version 1.0 of the ModSpec

|===
|*Name* |*Organization*
| Simon Cox | CSIRO
| David Danko | ESRI
| James Greenwood | SeiCorp, Inc.
| John R. Herring | Oracle USA
| Andreas Matheus | University of the Bundeswehr -- ITS
| Richard Pearsall | US National Geospatial-Intelligence Agency (NGA)
| Clemens Portele | interactive instruments GmbH
| Barry Reff | US Department of Homeland Security (DHS)
| Paul Scarponcini | Bentley Systems, Inc.
| Arliss Whiteside | BAE Systems - C3I Systems
|===

[.preface]
== Revision history

This is the second normative version of this document.

[.preface]
== Future work

Improvements to this document will be made based on implementation and changing technical requirements.

