[[cls-6]]
== Requirements Class: Part 1 UML

This clause defines the key concepts and requirements that represent Part 2 of the ModSpec.

=== The ModSpec and the "Form" of a standard

NOTE: For OGC Standards, the assumption is that documents are in a commonly used
logical form (template). 

In informative sections, the use of the word "will" implies that something is an implication of a requirement. The "will" statements are not requirements but explain the consequence of requirements.

The ModSpec defines a "requirement" of a standard as an atomic testable
criterion. See the formal definition of requirement in <<term-requirement>>

[[cls-6-1]]
=== Optional Requirements class: UML model extension to the core

If the organizing mechanism for the data model used in the standard is an object model, then the
mapping from parts of the model to the requirements classes should follow the
logical mechanism described here.

The terminology used here is common to all versions of the UML standard, and may
be applied to any such version.

First, by the requirements above, the extension relationship of this conformance
test class to the core will be made explicit.

include::../requirements/requirements_class_uml.adoc[]

Any conformant UML extension will comply with the ModSpec Core requirements class.

[[req-01]]
include::../requirements/uml/REQ001.adoc[]

Assuming all legitimate direct package dependencies are included in the UML model,
the conformance/requirements class associated to a package stem:[A] will directly
reference the conformance/requirements class associated to another package stem:[B],
if and only if stem:[A] is dependent on stem:[B]. Indirect dependencies will be
dealt with as the conformance classes cascade.

This clause uses UML terminology, but other object modeling languages and, if
needed, the object code itself can be mapped to a UML model. 

[[req-02]]
include::../requirements/uml/REQ002.adoc[]

[[req-03]]
include::../requirements/uml/REQ003.adoc[]

NOTE: External packages having predated the current version of the standard will
not normally have dependencies to packages within the standard.

Other dependencies (indirect) will arise from the transitive closure of the above
direct dependencies. That means if stem:[A] depends on stem:[B], and stem:[B]
depends on stem:[C] then stem:[A] depends on stem:[C]. Since these indirect
dependencies will show up in the cascade of included conformance tests based solely
on the direct dependencies, we can ignore them for effects on structure.

Since a package can consist solely of other packages, there is always the capability
to define in UML a single package that will correspond to a particular requirements
class and its associated conformance class.

[[req-04]]
include::../requirements/uml/REQ004.adoc[]

[[req-05]]
include::../requirements/uml/REQ005.adoc[]

The class definitions are the "requirements" of a UML expressed standard. Therefore, the
logical consequence of the above is to organize requirements classes based on leaf
packages.

[[req-06]]
include::../requirements/uml/REQ006.adoc[]

If a requirement uses or refers to elements of more than one package, then one of
the packages will be called the source of the requirement, and the other targets.
The requirement with the same source package will always be associated with the same
requirements module and/or class.

[[req-07]]
include::../requirements/uml/REQ007.adoc[]

This is actually a derived requirement and is repeated here for emphasis.

This dependency of requirements classes will be consistent with the usual mechanism
for describing the source and target of dependencies between packages. By Clause
<<req-22>> in the Core, only classes in the source requirements class will be affected by the
requirement.

In UML, source and target dependency relations are defined in such a way that the
source of the relation is dependent on the target of the relation.

[[req-08]]
include::../requirements/uml/REQ008.adoc[]

This means that the dependency graph of the UML packages parallels in some sense the
extension diagram of the requirements/conformance classes. If all leaf
packages of the model are moved into "requirements class packages" containing their
corresponding modeling packages the model then satisfies the following
recommendation: 

*#Each requirements class in a conformant standard should be
associated to one and only one UML package (which may contain sub-packages for a
finer level of structure). If the core requirements class contains only
recommendations, it may be an exception to this.#*

[[req-09]]
include::../requirements/uml/REQ009.adoc[]

[[req-10]]
include::../requirements/uml/REQ010.adoc[]

For example, if two classes have a two-way navigable association, then these two
classes must be (transitively) in the same conformance requirements class package.

The hierarchical structure of a UML model is based on UML classes, residing in UML
packages. UML packages can then reside in larger UML packages. Although there is
nothing to demand it, it is a common practice to move all classes down the hierarchy
to leaf packages. Leaf packages are those that contain only classes (that is,
contain no smaller subpackages). Classes can act as packages in the sense that a UML
class can contain a locally defined class whose scope is the class itself. For our
purposes, we will consider a class and its contained local classes to all be in the
package of the original class.

[[req-11]]
include::../requirements/uml/REQ011.adoc[]

