[.preface]
== Preface

This OGC member developed and approved document, referred to as the `ModSpec: Part 3`, defines an optional requirements class for the XML model extension the ModSpec core.

The ModSpec: Core Standard defines a model and related requirements 
and recommendations for writing and structuring modular standards documents. Further, this model is designed to enable 
consistent and verifiable testing of implementations of a standard that claim conformance. The ModSpec is a meta-standard: 
A standard specifying requirements for crafting and documenting modular and testable standards. 

The goals of using the ModSpec are:

- To define characteristics and a structure for the development of modular standards which will minimize the difficulty 
in writing testable standards while maximizing usability and interoperability.
- To ensure that a standard specifies requirements in a common and consistent manner and that these requirements are testable.

Suggested additions, changes, and comments on this document are welcome and
encouraged. Such suggestions may be submitted by creating an issue in the GitHub 
repository for this document (https://github.com/opengeospatial/ogc-modspec).

[.preface]
== Document terms and definitions

This document uses the standard terms defined in Subclause 5.3 of [OGC 05-008], which
is based on the ISO/IEC Directives, Part 2. Rules for the structure and drafting of
International Standards. In particular, the word "shall" (not "must") is the
imperative verb form used to indicate a requirement to be strictly followed to
conform to this standard.

[.preface]
== Document editors

The following OGC Members participated in editing this document:

[%unnumbered]
|===
^h| Person ^h| Organization Represented
| Carl Reed | Carl Reed & Associates
| John Herring, PhD | Oracle
|===

[.preface]
== Document Contributors

The following OGC Members contributed and participated in developing Version 1.1 of the ModSpec.

[%unnumbered]
|===
^h| Person ^h| Organization Represented
| Carl Reed, PhD| Carl Reed
| Chuck Heazel | Heazeltech
| Jeff Yutzler | ImageMatters
|===

[.preface]
== Submitting organizations

The following OGC Members support the ModSpec Version 1.1 submission

[%unnumbered]
|===
^h| Organization
| Carl Reed & Associates |
| Heazeltech |
| ImageMatters/Tema
| UK Met Office |
|===

[.preface]
== Revision history

This is the second normative version of this document.
