[.preface]
== Introduction

This OGC Policy specifies rules for the internal structure and organization of an OGC Standard. This OGC Policy is designed to enable the clear and concise specification of requirements (the _shalls_ or _musts_ in a standard) that fully supports the ability to define implementable conformance tests. The goal is to enable implementations of a standard to be tested and deemed _conformant_ . . . or not.

An OGC standard presents requirements , which must be satisfied by passing the tests of the conformance suite. These tests are organized into conformance classes, each of which represents a
mechanism for partial satisfaction of the standard. This results in the OGC standard having a modular structure, where each requirements class has a corresponding conformance (test) class. In a well written standard, the normative clauses and any model or schema are organized in a manner that parallels the requirements and conformance clauses.

NOTE: The approach modelled in this Policy has been referred to as the "core and extension model" due to its
insistence on a modular structure throughout all parts of a standard and its implementation.
