[.preface]
== Preface

This standard contains requirements for writing standards to be used for any document
whose eventual purpose is the specification of requirements for software, services or
data structures.

Suggested additions, changes, and comments on this standard are welcome and
encouraged. Such suggestions may be submitted through the OGC change request system
(http://www.opengeospatial.org/standards/cr).

[.preface]
== Document terms and definitions

This document uses the standard terms defined in Subclause 5.3 of [OGC 05-008], which
is based on the ISO/IEC Directives, Part 2. Rules for the structure and drafting of
International Standards. In particular, the word "shall" (not "must") is the
imperative verb form used to indicate a requirement to be strictly followed to
conform to this standard.

[.preface]
== Document contributors

The following voting members of the Standards Working Group participated in editing
this document:

[%unnumbered]
|===
^h| Person ^h| Organization Represented
| Simon Cox | CSIRO
| David Danko | ESRI
| James Greenwood | SeiCorp, Inc.
| John R. Herring | Oracle USA
| Andreas Matheus | University of the Bundeswehr -- ITS
| Richard Pearsall | US National Geospatial-Intelligence Agency (NGA)
| Clemens Portele | interactive instruments GmbH
| Barry Reff | US Department of Homeland Security (DHS)
| Paul Scarponcini | Bentley Systems, Inc.
| Arliss Whiteside | BAE Systems - C3I Systems
|===

[.preface]
== Revision history

This is the first normative version of this document.

[.preface]
== Changes to the OGC Abstract Specification

The OpenGIS® Abstract Specification and Standard will require changes to accommodate
the contents of this document. At their next revision, any volume of the abstract
specification or implementation standards will have to be made to conform to the
requirements here.

[.preface]
== Future work

Any needed improvements in this document will be made as experience with using it
increases.
