[.preface]
== Preface

This OGC member developed and approved document defines a model and related requirements and recommendations for writing and structuring modular standards documents. Further, this model is designed to enable the consistent and verifiable testing of implementations of a standard that claim conformance.

The goal is to ensure that a standard specifies requirements in a common and consistent manner and that these requirements are testable.

NOTE: For OGC only: Any new OGC Standard, abstract specification, or major revision of an existing OGC Standard shall comply with the requirements stated in this document.

NOTE: Historically, this document has been known and abbreviated as the "ModSpec". For continuity and ease of understanding this document may also be refered to as the "OGC ModSpec".

Suggested additions, changes, and comments on this this document are welcome and
encouraged. Such suggestions may be submitted through the OGC Change Request System
(http://www.opengeospatial.org/standards/cr) or by creating an issue in the GitHub repository for this document (https://github.com/opengeospatial/ogc-modspec).

[.preface]
== Document terms and definitions

This document uses the standard terms defined in Subclause 5.3 of [OGC 05-008], which
is based on the ISO/IEC Directives, Part 2. Rules for the structure and drafting of
International Standards. In particular, the word "shall" (not "must") is the
imperative verb form used to indicate a requirement to be strictly followed to
conform to this standard.

[.preface]
== Document contributors

The following OGC Members participated in editing this document:

[%unnumbered]
|===
^h| Person ^h| Organization Represented
| Carl Reed | Carl Reed & Associates
|===

[.preface]
== Acknowledgements

The following OGC Members contributed and particpated in developing the original version of this Policy document.

[%unnumbered]
|===
^h| Person ^h| Organization Represented
| Simon Cox | CSIRO
| David Danko | ESRI
| James Greenwood | SeiCorp, Inc.
| John R. Herring | Oracle USA
| Andreas Matheus | University of the Bundeswehr -- ITS
| Richard Pearsall | US National Geospatial-Intelligence Agency (NGA)
| Clemens Portele | interactive instruments GmbH
| Barry Reff | US Department of Homeland Security (DHS)
| Paul Scarponcini | Bentley Systems, Inc.
| Arliss Whiteside | BAE Systems - C3I Systems
|===

[.preface]
== Revision history

This is the second normative version of this document.

[.preface]
== Future work

Improvements to this document will be made based on implementation and changing technical requirements.
