[[cls-1]]
== Scope
This OGC Standard for Designing and Writing Modular Standards, also known as the `ModSpec`:

- Specifies rules for the internal structure and organization of a standard. 
- Defines requirements for specifying the structure of a standards document as organized sets of criteria, those that are to be tested ("requirements") and those that are not tested ("recommendations" and "permissions"). 
- Is designed to enable the clear and concise specification of requirements (the _shalls_ or _musts_ in a standard) that fully supports the ability to define implementable conformance tests. 
- Formalizes implementing the requirements specified in the ModSpec so that reusable, modular standards can be developed.

The standardization goal of the ModSpec is to define characteristics and a structure for the specification of modular and testable Standards 
that will encourage implementation by minimizing difficulty determining
requirements, mimicking implementation structure, and maximizing usability and
interoperability. The ultimate goal of this approach is to enable interoperable implementations of a standard to be tested and deemed _conformant_ or not.

Therefore, a standard that follows the rules specified in the ModSpec presents requirements organized in requirements classes which must be satisfied by passing the tests defined in a conformance suite (also known as the Abstract Test Suite in an OGC Standard). These tests are organized into conformance classes, each of which represents a mechanism for partial satisfaction of the standard. This results in a standard having a modular structure, where each requirements class has a corresponding conformance (test) class. In a well written standard, the normative clauses and any model or schema are organized in a manner that parallels the requirements and conformance clauses. A goal of the design pattern is the ability to define requirements classes and associated conformance classes that can be used across multiple standards. The approach modelled in the ModSpec has been referred to as the "core and extension model" due to its insistence on a modular structure throughout all parts of a standard and its implementation.

There are numerous examples of requirements/conformance classes that can be used not only in OGC Standards, but for geospatially focused standards defined by other organizations and Standards Development Organizations (SDOs). Some OGC examples can be found in the https://docs.ogc.org/is/19-072/19-072.html[OGC API - Common Part 1: Core Standard] and in the https://github.com/opengeospatial/cdbswg/blob/master/cdb-2.0/cdb-core-crs-requirements-class.adoc[CDB 2.0 Standard CRS Requirements Module]. By formally implementing the requirements specified in the ModSpec, reusable, testable, modular standards can be developed.

[[things-to-know]]
=== Understanding the ModSpec

Reading the Terms and Definitions clause and Clause <<Terms and Definitions, cls-4>> will help understanding the content and
requirements stated in this document.

<<Annex C,annex-C>> defines the UML model upon which the ModSpec is
based. Annex C also contains informal and non-normative definitions ordered for ease
of understanding. These two sections can be read first to aid in the understanding of
the rest of the document.

NOTE: For OGC Standards work, the word “standard” in the ModSpec applies to all OGC draft standards, approved standards, draft Abstract Specifications, and approved Abstract Specifications. The exceptions are OGC Abstract Specifications that originate in ISO or Community Standards that are developed external to the OGC and then submitted to the OGC.

NOTE: Please note that the ModSpec has been approved by the OGC Membership as a policy directive for the development and revision of any OGC Standard or Abstract Specification that has requirements. However, the ModSpec is written to be non-OGC specific and can be used by any Standards Development Organization (SDO) as a formal guide for structuring a standards document.

NOTE: In informative sections, the word "will" implies that something is an implication of a requirement. The "will" statements are
not requirements, but explain the consequence of requirements.

==== ModSpec document structure

Version 2.0 of the ModSpec is split into a Core standard and multiple Parts. These are:

- Core: contains all the core requirements and informational text that define the model and internal structure of a standard.
- Part 1: UML Model requirements 
- Part 2: XML and Schematron Model requirements 

Future Parts to the ModSpec Standard may include:

- Part 3: RDF/OWL requirements
- Part 4: JSON Schema

