[[cls-4]]
== Terms and definitions by category

[.boilerplate]
=== {blank}

For the purposes of this document, the following terms and definitions shall apply.
Terms not defined here take their meaning from computer science or from their
Standard English (common US and UK) meanings. The form of the definitions is
defined by ISO Directives.

Many of these definitions depend upon the model given in <<annex-C,Annex C: ModSpec UML Model, Semantics, and Definitions>>.

=== Building Blocks Terms and Definitions

[[BuildingBlock-definition]]

==== Building Block

a <<RequirementsClass-definition,requirements class>> or a <<RequirementsModule-definition,requirements module>> with no direct dependencies on other requirements classes or modules and their associated <<ComplianceClass-definition,compliance test class>> or <<ComplianceModule-definition,compliance test module>>. 

=== General Terms and Definitions

[[BestPractice-definition]]

==== Best Practice

a <<Specification-definition,specification>> that has been approved by a legitimate Standards Body as a recommendation for implementation.  

[[InformativeStatement-definition]]

==== Informative Statement

expression in a document conveying non-normative information

NOTE: Includes all statements in a document not part of the normative requirements, recommendations, permissions, or conformance tests. Included for completeness. 

[[Module-definition]]

==== Module

each of a set of standardized parts or independent units that can be used to construct a more complex structure

Note: The concept ‘module’ is key to the ModSpec structure and model. Modules have a direct relationship to the concept of building blocks. The power of the concept is that modules can be reused in different systems (specify once, use many). Modules can be imported from other programs. Modules can be replaced without affecting the rest of the system. 

[[NormativeStatement-definition]]

==== Normative Statement

expression in a document conveying information required to define conformance

NOTE:  Includes all normative statements in a document including requirements, recommendations, permissions, and conformance tests. Included for completeness. 

[[Specification-definition]]

==== Specification

document containing recommendations, requirements, permissions, and conformance tests

NOTE:  This definition is included for completeness. 

NOTE:  In the OGC, there are Abstract Specifications and Implementation Standards. Abstract Specifications may of may not be testable. Further, Abstract Specifications may not be directly implementable. Implementation Standards are always testable and contain a conformance test suite. 

[[Standard-definition]]

==== Standard

a <<Specification-definition,specification>> that has been approved by a legitimate Standards Body 

NOTE:  This definition is included for completeness. Standard and specification can apply to the same document. While specification is always valid, standard only applies after the adoption of the document by a legitimate standards organization.  

NOTE:  A standard should consist primarily of Normative Statements. The goal should be for the standard to be concise. Supporting information can be provided through a users guide. 

[[Statement-definition]]

==== Statement

expression in a document conveying information 

[[UsersGuide-definition]]

==== Users Guide

Non-normative information that assists in understanding a standard but is not required to implement the standard.   

=== Concepts Terms and Definitions

[[CertificateOfConformance-definition]]

==== Certificate Of Conformance

evidence of conformance to all or part of a standard, awarded for passing one or more of the conformance test classes specified in that standard 

NOTE:  Certificates‖ do not have to be instantiated documents; having proof of passing the conformance test class is sufficient. For example, the OGC currently keeps an online list of conformant applications at http://www.opengeospatial.org/resource/products. 
Each certificate of conformance is awarded to a standardization target.  

[[CoreRequirementsClass-definition]]

==== Core Requirements Class

unique requirements class that must be satisfied by any conformant standardization targets associated to the standard

NOTE:  The core requirements class is unique because if it was possible to have more than one, then each core would have to be implemented to pass any conformance test class, and thus would have to be contained in any other core. The core may be empty, or all or part of another standard or related set of standards. 

The core can refer to this requirements class, its associated conformance test class or the software module that implements that requirements class.  

[[Dependency-definition]]

==== Dependency

a module (the target) which is used, produced or associated to by an implementation of the source module. 

[[DirectDependency-definition]]

==== Direct Dependency

another requirements class (the dependency) whose requirements are defined to also be requirements of this requirements class

NOTE: A direct dependency (of a requirements class) of the current requirements class will have the same standardization target as the current requirements class. This is another ways of saying that the current requirements class extends, or uses all the aspects of the direct dependency (or a requirements class). Any tests associated to this dependency can be applied to this requirements class. 

When testing a direct dependency of a requirements class, the standardization target is directly subject to the test in the specified conformance test class of the direct dependency of a requirements class.  

[[Extension-definition]]

==== Extension

requirements class which has a direct dependency on another requirements class 

NOTE: Here an extension of a requirements class is defined on requirements class so that their implementation may be software extensions in a manner analogous to the extension relation between the requirements classes.  

[[IndirectDependency-definition]]

==== Indirect Dependency

requirements class with a different standardization target which is used, produced or associated to by the implementation of this requirements class 

NOTE: In this instance, as opposed to the direct dependency of a requirements class, the test against the consumable or product used or produced by the requirements class does not directly test the requirements class, but tests only its side effects. Hence, a particular type of feature service could be required to produce valid XML documents, but the test of validity for the XML document is not directly testing the service, but only indirectly testing the validity of its output. Direct dependencies test the same standardization target, but indirect dependencies test related but different standardization targets. +
For example, if a DRM-enabled service is required to have an association to a licensing service, then the requirements of a licensing service are indirect requirements for the DRM-enabled service. Such a requirement may be stated as the associated licensing service has a certificate of conformance of a particular kind.  

[[LeafPackage-definition]]

==== Leaf Package

UML model package that does not contain any subpackages, but contains classifiers 
[UML]  

[[Profile-definition]]

==== Profile

specification or standard consisting of a set of references to one or more base standards and/or other profiles, and the identification of any chosen conformance test classes, conforming subsets, options and parameters of those base standards, or profiles necessary to accomplish a particular function. 

NOTE:  In the usage of the ModSpec, a profile will be a set of requirements classes or conformance classes (either preexisting or locally defined) of the base standards.

This means that a standardization target being conformant to a profile implies that the same target is conformant to the standards referenced in the profile.

[ISO/IEC TR 10000-1]    

=== Core Terms and Definitions

[[ConformanceClass-definition]]

==== Conformance Class

a set of <<ConformanceTest-definition,conformance tests>> that must be passed to receive a single <<CertificateOfConformance-definition,certificate of conformance>>

NOTE:  When no ambiguity is possible, the word test may be left out, so conformance test class may be called a conformance class. +
In the ModSpec, the set of <<Requirement-definition,requirements>> tested by the conformance tests within a <<ConformanceClass-definition,conformance class>> is a <<RequirementsClass-definition,requirements class>> and its dependencies. Optional requirements will be in a separate requirements class with other requirements that are part of the same option. Each requirements class corresponds to a separate conformance class +
Each requirements class will be in a 1 to 1 correspondence to a similarly named conformance class that tests all of the requirements in the requirements class. +
All requirements in a conformance class will have the same standardization target type.  

[[ConformanceModule-definition]]

==== ConformanceModule

a set of related conformance classes and their associated components. 

[[ConformanceSuite-definition]]

==== Conformance Suite

set of <<ConformanceModule-definition,conformance modules>> that define <<ConformanceTest-definition,tests>> for all <<Requirement-definition,requirements>> of a <<Standard-definition,standard>> or abstract specification

NOTE:  The *conformance suite* is the union of all *conformance modules* and their associated <<ConformanceClass-definition,conformance classes>>. It is by definition the *conformance class* of the entire *standard* or *abstract specification*.  

[[ConformanceTest-definition]]

==== Conformance Test

test, abstract or real, of one or more <<Requirement-definition,requirements>> contained within a standard, or set of standards  

[[ConformanceTestMethod-definition]]

==== Conformance Test Method

How an implementation of the standard is tested for conformance. Testing may be automated, manual, or a hybrid.

NOTE: Testing by an independent second party is recommended.

[[Model-definition]]

==== Model

A representation of those aspects of the standardization target type which are to be governed by a standard. The model captures both the conceptual and logical properties of the standardization target type. The requirements promulgated by a standard should be expressed in terms of those conceptual and logical properties.

In short, the model provides the vocabulary for expressing requirements. 

[[Permission-definition]]

==== Permission

uses “may” and is used to prevent a requirement from being “over interpreted” and as such is considered to be more of a “statement of fact” than a “normative” condition. 

[[Principal-definition]]

==== Principal

TBD - Undefined in 08-131r3. 

[[Recommendation-definition]]

==== Recommendation

expression in the content of a standard conveying that among several possibilities one is recommended as particularly suitable, without mentioning or excluding others, or that a certain course of action is preferred but not necessarily required, or that (in the negative form) a certain possibility or course of action is deprecated but not prohibited 

NOTE:  Although using normative language, a recommendation is not a requirement. The usual form replaces the shall (imperative or command) of a requirement with a should (suggestive or conditional). 

NOTE:  Recommendations are not tested and therefore have no related conformance test.

[ISO Directives Part 2] 

[[Requirement-definition]]

==== Requirement

expression in the content of a <<Standard-definition,standard>> conveying criteria to be fulfilled if compliance with the standard is to be claimed and from which no deviation is permitted
[ISO Directives Part 2] 

NOTE:  Each requirement is a normative criterion for a single type of <<StandardizationTarget-definition,standardization target>>. In the ModSpec, requirements are associated to <<ConformanceTest-definition,conformance tests>> that can be used to prove compliance to the underlying criteria by the standardization target. 

NOTE: The implementation of a requirement is dependent on the type of standard being written. A data standard requires data structures, but a procedural standard requires software implementations. The view of a standard in terms of a set of testable requirements allows us to use set descriptions of both the standard and its implementations.

NOTE: The specification of a requirement is usually expressed in terms of a model of the standardization target type, such as a UML model, or an XML or SQL schema. Anything without a defined test is a-priori not testable and thus would be better expressed as a recommendation. 

NOTE: Requirements use normative language and in particular are commands and use the imperative "shall" or similar imperative constructs. Statements in standards which are not requirements and need to be either conditional or future tense normally use "will" and should not be confused with requirements that use "shall" imperatively  

[[RequirementsClass-definition]]

==== Requirements Class

aggregate of all <<Requirement-definition,requirements>> with a single <<StandardicationTargetType-definition,standardization target type>> that must all be satisfied to pass a <<ConformanceClass-definition,conformance test Class>>.

NOTE:  There is some confusion possible here, since the testing of <<IndirectDependency-definition,indirect dependencies>> seems to violate this definition. But the existence of an indirect dependency implies that the test is actually a test of the existence of the relationship from the original target to something that has a property (satisfies a condition or requirement from another requirements class).  

[[RequirementsModule-definition]]

==== Requirements Module

a set of related requirement classes and their associated components. 

[[StandardizationGoal-definition]]

==== Standardization Goal

a concise statement of the problem that the standard helps address and the strategy envisioned for achieving a solution. This strategy typically identifies real-world entities that need to be modified or constrained. At the abstract level, those entities are the <<StandardizationTargetType-definition,Standardization Target Types>>.  

[[StandardizationTarget-definition]]

==== Standardization Target

entity to which some <<Requirement-definition,requirements>> of a <<Standard-definition,standard>> apply

NOTE:   The standardization target is the entity which may receive a certificate of conformance for a requirements class.  

[[StandardizationTargetType-definition]]

==== Standardization Target Type

type of entity or set of entities to which the <<Requirement-definition,requirement>> of a <<Standard-definition,standard>> apply

NOTE:  For example, the standardization target type for The OGC API – Features Standard are Web APIs. The standardization target type for the CDB Standard is “datastore”. It is important to understand that a standard’s root standardization target type can have sub-types, and that there can be a hierarchy of target types. For example, a Web API can have sub types of client, server, security, and so forth. As such, each requirements class can have a standardization target type that is a sub-type of the root. 

[[TestType-definition]]

==== TestType

TBD - undefined in 08-131r3   

=== Types Terms and Definitions

[[DateTime-definition]]

==== DateTime

[[RichText-definition]]

==== RichText

 

[[String-definition]]

==== String

==== will
In informative sections, the word "will" implies that something is an implication of a requirement. The "will" statements are
not requirements, but explain the consequence of requirements.
