[[cls-4]]
== Terms and definitions

[.boilerplate]
=== {blank}

For the purposes of this document, the following terms and definitions shall apply.
Terms not defined here take their meaning from computer science or from their
Standard English (common US and UK) meanings. The form of the definitions is
defined by ISO Directives.

Many of these definitions depend upon the model given in <<Annex C,annex-C>>.

=== building block

a requirements class or a requirements module with no direct dependencies on other requirements classes or modules and their associated compliance test class or compliance test module.

=== certificate of conformance

evidence of conformance to all or part of a standard, awarded for passing one or
more of the {{conformance test class,conformance test classes}} specified in
that standard

[NOTE]
====
"Certificates" do not have to be instantiated documents. Having proof of passing
the conformance test class is sufficient. For example, the OGC currently keeps
an online list of conformant applications at https://www.ogc.org/resources/certified-products/.

Each certificate of conformance is awarded to a {{standardization target}}.
====

=== conformance test

test, abstract or real, of a single {{requirement,requirements}} contained
within a standard, or set of standards

=== conformance test case

test for a particular requirement or a set of related requirements

NOTE: When no ambiguity, the word "case" may be omitted. i.e.
{{conformance test}} is the same as
{{conformance test case}}.

=== conformance test module

set of related tests for a given requirements module all with the same standardization target

[NOTE]
====
When there is no ambiguity, the word "test" may be omitted. i.e. {{conformance test module}}
is the same as *conformance module*. Conformance modules may be nested in a hierarchical way.
====

=== conformance test class
alt:[conformance test level]

set of {{conformance tests,conformance test}} that must be passed to receive a single {{certificate of conformance}}

[NOTE]
====
When no ambiguity is possible, the word "test" may be left out, so {{conformance test class}}
maybe called a <<conformance-class,_conformance class_>>.

In the ModSpec, the set of {{requirement,requirements}} tested by the
conformance tests within a <<conformance-class,_conformance class_>> is a
{{requirements class}} and its dependencies. Optional {{requirement,requirements}} will
be in a separate {{requirements class}} with other {{requirement,requirements}}
that are part of the same option. Each {{requirements class}} corresponds to a
separate <<conformance-class,conformance class>>

Each requirements class will be in a 1 to 1 correspondence to a similarly named
<<conformance-class,_conformance class_>> that tests all of the
{{requirements class,requirements class's}} {{requirement,requirements}}.

All {{requirement,requirements}} in a <<conformance-class,_conformance class_>>
will have the same {{standardization target}}.
====

=== conformance suite
alt:[conformance test suite]
alt:[abstract test suite]

set of <<conformance-class,_conformance classes_>> that define tests for all {{requirement,requirements}} of a standard or abstract specification

[NOTE]
====
The {{conformance suite}} is the union of all <<conformance-class,_conformance classes_>>. It is by definition the
<<conformance-class,_conformance class_>> of the entire standard or abstract specification.

In theModSpec, each {{requirement}} is mandatory within its <<conformance-class,conformance class>> and each {{requirement}} is tested in at least one {{conformance test}}.
====

=== core requirements class

unique {{requirements class}} that must be satisfied by any conformant
{{standardization target,standardization targets}} associated to the
standard

[NOTE]
====
The core {{requirements class}} is unique because if it were possible to have
more than one, then each *core* would have to be implemented to pass any
{{conformance test class}}, and thus would have to be contained in any other
*core*. The *core* may be empty, or all or part of another standard or related
set of standards.

The "*core*" can refer to this {{requirements class}}, its associated
{{conformance test class}} or the software module that implements that
requirements class.
====

=== direct dependency (of a requirements class)

another {{requirements class}} (the dependency) whose {{requirement,requirements}} are defined to also be
{{requirement,requirements}} of this
{{requirements class}}

[NOTE]
====
A {{direct dependency (of a requirements class), direct dependency}}
of the current {{requirements class}} will have the same
{{standardization target}} as the current
{{requirements class}}. This is another ways of saying that the current
{{requirements class}} extends, or uses all the aspects of the
{{direct dependency (of a requirements class), direct dependency}}.
Any tests associated with this
{{direct dependency (of a requirements class),dependency}} can be applied to this
{{requirements class}}.

When testing a
{{direct dependency (of a requirements class), direct dependency}}, the
{{standardization target}} is directly subject to the test in the specified
{{conformance test class}} of the {{direct dependency (of a requirements class), direct dependency}}.
====

=== indirect dependency (of a requirements class)

{{requirements class}} with a different
{{standardization target}} which is used, produced or associated to by the
implementation of this {{requirements class}}

[NOTE]
====
In this instance, as opposed to the
{{direct dependency (of a requirements class),direct dependency}},
the test against the consumable or product used
or produced by the {{requirements class}} does not directly test the
{{requirements class}}, but tests only its side effects. Hence, a particular
type of feature service could be required to produce valid XML documents, but
the test of validity for the XML document is not directly testing the service,
but only indirectly testing the validity of its output.
{{direct dependency (of a requirements class), Direct dependencies}}
test the same {{standardization target}}, but
{{indirect dependency (of a requirements class), indirect dependencies}}
test related but different {{standardization target,standardization targets}}.

For example, if a DRM-enabled service is required
to have an association to a licensing service, then the requirements of a
licensing service are indirect requirements for the DRM-enabled service. Such a
requirement may be stated as the associated licensing service has a
{{certificate of conformance}} of a particular kind.
====

=== extension (of a requirements class)

{{requirements class}} which has a
{{direct dependency (of a requirements class), direct dependency}} on another
{{requirements class}}

NOTE: Here {{extension (of a requirements class),extension}} is
defined on {{requirements class}} so that their implementation may be
software extensions in a manner analogous to the extension relation between the
{{requirements class,requirements classes}}.

=== general recommendation

recommendation applying to all entities in a standard

=== home (of a requirement or recommendation)

official statement of a {{requirement}} or {{recommendation}} that is the
precedent for any other version repeated or rephrased elsewhere in a standard

[NOTE]
====
Explanatory text associated with normative language often repeats or rephrases the
requirement to aid in the discussion and understanding of the official version
of the normative language. Since such restatements are often less formal than
the original source and potentially subject to alternate interpretation, it is
important to know the location of the *home* official version of the language.
====

=== model
alt:[abstract model]
alt:[conceptual model]

theoretical construct that represents something, with a set of variables and a
set of logical and quantitative relationships between them.

=== module

one of a set of separate parts that can be joined together to form a larger object

[.source]
Cambridge Dictionary

=== optional requirements class

An optional requirements class may or may not be implemented or specified in a profile or extension. However, if a profile, extension, or implementation specifies the use of an optional requirements class, then every requirement in that requirements class _shall_ be implemented.

=== part of a requirment
Collection of requirements that are parts to a requirement. Satisfaction of all requirement parts are necessary for this requirement to be satisfied. The use of `parts` is optional.

=== permission 

uses "may" and is used to prevent a requirement from being "over interpreted" and as such is considered to be more
of a "statement of fact" than a "normative" condition. 

=== profile

specification or standard consisting of a set of references to one or more base
standards and/or other profiles, and the identification of any chosen
{{conformance test class,conformance test classes}},
conforming subsets, options and parameters of those base standards, or
profiles necessary to accomplish a particular function.

[NOTE]
====
In the usage of this Policy, a profile will be a set of requirements classes
or conformance classes (either preexisting or locally defined) of the base
standards.

This means that a {{standardization target}} being conformant to a profile
implies that the same *target* is conformant to the standards referenced in the
{{profile}}.
====

[.source]
<<iso10000-1>>

=== recommendation

expression in the content of a standard conveying that among several
possibilities one is recommended as particularly suitable, without mentioning or
excluding others, or that a certain course of action is preferred but not
necessarily required, or that (in the negative form) a certain possibility or
course of action is deprecated but not prohibited

NOTE: Although using normative language, a {{recommendation}} is not
a {{requirement}}. The usual form replaces the "shall" (imperative or
command) of a {{requirement}} with a "should" (suggestive or
conditional).

NOTE: Recommendations are *not* tested and therefor have no related conformance test.

[.source]
<<iso-dp2>>

=== requirement

expression in the content of a standard conveying criteria to be fulfilled if
compliance with the standard is to be claimed and from which no deviation is permitted

[NOTE]
====
Each {{requirement}} is a normative criterion for a single
*type of standardization target*. In the ModSpec, requirements are
associated to {{conformance test, conformance tests}} that can be used to prove
compliance to the underlying criteria by the {{standardization target}}.

The implementation of a {{requirement}} is dependent on the type of
standard being written. A data standard requires data structures, but
a procedural standard requires software implementations. The view of a
standard in terms of a set of testable {{requirement,requirements}} allows us to
use set descriptions of both the standard and its implementations.

{{requirement,Requirements}} use normative language and are
commands and use the imperative "shall" or similar imperative constructs.
Statements in standards which are not requirements and need to be either
conditional or future tense normally use "will" and should not be confused with
requirements that use "shall" imperatively.
====

[.source]
<<iso-dp2>>

=== requirements class

aggregate of all {{requirements,requirement}} with a single standrdization target that
must all be satisfied to pass a {{conformance test class}}

NOTE: There is some confusion possible here, since the testing of indirect
dependencies seems to violate this definition. But the existence of an indirect
dependency implies that the test is actually a test of the existence of the
relationship from the original target to something that has a property
(satisfies a condition or requirement from another requirements class).

=== requirements module

collection of {{requirement class,requirements classes}}, 
{{recommendation,recommendations}} and {{permission,permissions}} with a
single {{standardization target}}

=== specification

document containing {{recommendation,recommendations}},
{{requirement,requirements}} and {{conformance test, conformance tests}} for
those {{requirement,requirements}}

[NOTE]
====
This definition is included for completeness. See <<cls-5-3>>.

This does not restrict what else a standard may contain, as long as it does
contain the three types of element cited.
====

=== standard

document that has been approved by a legitimate Standards Body

[NOTE]
====
This definition is included for completeness. {{standard,Standard}} and
{{specification}} can apply to the same document. While {{specification}} is
always valid, {{standard}} only applies after the adoption of the document by a
legitimate standards organization.
====

=== standardization target

entity to which some {{requirement,requirements}} of a {{standard}} apply

NOTE: The {{standardization target}} is the entity which may receive a
{{certificate of conformance}} for a {{requirements class}}.

NOTE: Need to add examples! The standardization target of the CDB version 2.0 CRS Requirements Classes is to ensure that an implementation clearly defines (with metadata) the CRS for a CDB compliant datastore. 

=== standardization target type

type of entity or set of entities to which the {{requirement,requirements}} of a
{{standard}} apply

NOTE: For example, the standardization target type for The OGC API – Features Standard are Web APIs. The standardization target type for the CDB Standard is "datastore". It is important to understand that a standard's root standardization target type and can have sub-types and that there can be a hierarchy of target types. For example, a Web API can have sub types of client, server, security, and so forth. As such, each requirements class can have a standardization target type that is a sub-type of the root.

=== statement

expression in a document conveying information

NOTE: Includes all statements in a document not part of the normative
{{requirement,requirements}},
{{recommendation,recommendations}} or
{{conformance test, conformance tests}}. Included for completeness.

[.source]
<<iso-dp2>>
