[[cls-4]]
== Terms and definitions by category

[.boilerplate]
=== {blank}

For the purposes of this document, the following terms and definitions shall apply.
Terms not defined here take their meaning from computer science or from their
Standard English (common US and UK) meanings. The form of the definitions is
defined by ISO Directives.

Many of these definitions depend upon the model given in <<annex-C,Annex C: ModSpec UML Model, Semantics, and Definitions>>.

=== Building Block Terms and Definitions

[[BuildingBlock-definition]]
==== building block

a <<RequirementsClass-definition,requirements class>> or a <<RequirementsModule-definition,requirements module>> with no direct dependencies on other requirements classes or modules and their associated <<ComplianceClass-definition,compliance test class>> or <<ComplianceModule-definition,compliance test module>>. 

=== General Terms and Definitions

[[BestPractice-definition]]

==== BestPractice

a <<Specification-definition,specification>> that has been approved by a legitimate Standards Body as a recommendation for implementation. 

[[InformativeStatement-definition]]

==== InformativeStatement

expression in a document conveying non-normative information

NOTE:  Includes all statements in a document not part of the normative requirements, recommendations, permissions, or conformance tests. Included for completeness. 

[[Module-definition]]

==== Module

each of a set of standardized parts or independent units that can be used to construct a more complex structure

NOTE: The concept ‘module’ is key to the ModSpec structure and model. Modules have a direct relationship to the concept of building blocks. The power of the concept is that modules can be reused in different systems (specify once, use many). Modules can be imported from other programs. Modules can be replaced without affecting the rest of the system. 

[[NormativeStatement-definition]]

==== NormativeStatement

expression in a document conveying information required to define conformance

NOTE:  Includes all normative statements in a document including requirements, recommendations, permissions, and conformance tests. Included for completeness. 

[[Specification-definition]]

==== Specification

document containing recommendations, requirements, permissions, and conformance tests

NOTE:  This definition is included for completeness. 

NOTE:  In the OGC, there are Abstract Specifications and Implementation Standards. Abstract Specifications may of may not be testable. Further, Abstract Specifications may not be directly implementable. Implementation Standards are always testable and contain a conformance test suite. 

[[Standard-definition]]

==== Standard

a <<Specification-definition,specification>> that has been approved by a legitimate Standards Body 

NOTE:  This definition is included for completeness. Standard and specification can apply to the same document. While specification is always valid, standard only applies after the adoption of the document by a legitimate standards organization.  

NOTE:  A standard should consist primarily of Normative Statements. The goal should be for the standard to be concise. Supporting information can be provided through a users guide. 

[[Statement-definition]]

==== Statement

expression in a document conveying information 

[[UsersGuide-definition]]

==== UsersGuide

Non-normative information that assists in understanding a standard but is not required to implement the standard.

==== will
In informative sections, the word "will" implies that something is an implication of a requirement. The "will" statements are
not requirements, but explain the consequence of requirements.

=== Concepts Terms and Definitions

[[CertificateOfConformance-definition]]

==== Certificate Of Conformance

evidence of conformance to all or part of a standard, awarded for passing one or more of the <<ConformanceClass-definition,conformance test classes>> specified in that standard 

NOTE:  Certificates do not have to be instantiated documents. Having proof of passing the conformance test class is sufficient. For example, the OGC currently keeps an online list of conformant applications at http://www.opengeospatial.org/resource/products. Each certificate of conformance is awarded to a standardization target.  

[[CoreRequirementsClass-definition]]

==== Core Requirements Class

unique requirements class that must be satisfied by any conformant standardization targets associated to the standard

NOTE:  The core requirements class is unique because if it was possible to have more than one, then each core would have to be implemented to pass any conformance test class, and thus would have to be contained in any other core. The core may be empty, or all or part of another standard or related set of standards. 

The core can refer to this requirements class, its associated conformance test class or the software module that implements that requirements class.  

[[Dependency-definition]]

==== Dependency

a module (the target) which is used, produced or associated to by an implementation of the source module. 

[[DirectDependency-definition]]

==== Direct Dependency

another requirements class (the dependency) whose requirements are defined to also be requirements of this requirements class

NOTE: A direct dependency (of a requirements class) of the current requirements class will have the same standardization target as the current requirements class. This is another ways of saying that the current requirements class extends, or uses all the aspects of the direct dependency (or a requirements class). Any tests associated to this dependency can be applied to this requirements class. 

When testing a direct dependency of a requirements class, the standardization target is directly subject to the test in the specified conformance test class of the direct dependency of a requirements class.  

[[Extension-definition]]

==== Extension

requirements class which has a direct dependency on another requirements class 

NOTE:: Here an extension of a requirements class is defined on requirements class so that their implementation may be software extensions in a manner analogous to the extension relation between the requirements classes.  

[[IndirectDependency-definition]]

==== Indirect dependency

requirements class with a different standardization target which is used, produced or associated to by the implementation of this requirements class 

NOTE: In this instance, as opposed to the direct dependency of a requirements class, the test against the consumable or product used or produced by the requirements class does not directly test the requirements class, but tests only its side effects. Hence, a particular type of feature service could be required to produce valid XML documents, but the test of validity for the XML document is not directly testing the service, but only indirectly testing the validity of its output. Direct dependencies test the same standardization target, but indirect dependencies test related but different standardization targets. +
For example, if a DRM-enabled service is required to have an association to a licensing service, then the requirements of a licensing service are indirect requirements for the DRM-enabled service. Such a requirement may be stated as the associated licensing service has a certificate of conformance of a particular kind.  

[[LeafPackage-definition]]

==== Leaf Package

UML model package that does not contain any subpackages, but contains classifiers 
[UML]  

[[Profile-definition]]

==== Profile

specification or standard consisting of a set of references to one or more base standards and/or other profiles, and the identification of any chosen conformance test classes, conforming subsets, options and parameters of those base standards, or profiles necessary to accomplish a particular function. 

NOTE:  In the usage of the ModSpec, a profile will be a set of requirements classes or conformance classes (either preexisting or locally defined) of the base standards.

This means that a standardization target being conformant to a profile implies that the same target is conformant to the standards referenced in the profile.

[ISO/IEC TR 10000-1]    
