[[annex-B]]
[appendix,obligation=normative]
== Changes required in the OGC Standards

NOTE: For OGC Standards only: No changes are required to existing OGC Standards

=== New standards and revisions to exissting standards

Any new standard, specification, or major revision of an existing standard shall
comply with the ModSpec in the structure of its internal models and its
conformance tests.

Failure to conform by a candidate standard to the ModSpec should be specifically
noted and reasons given for such non-compliance in the conformance clauses of any
new or new version of such candidate standards.

The adoption of such documents not compliant with the ModSpec shall be
considered as an authorized exception to the requirements of the ModSpec by the
approporiate authority, such as the OGC or ISO. The adoption of such
documents not compliant with the ModSpec shall be considered as an exception to
the requirements of the ModSpec by the authority (OGC) and shall be considered as an exception
to the rules of the authority such as the OGC and will require a two-thirds (2/3) majority ("Robert's
Rules") or as specified in the authorities Policy and Procedures for an exception to
procedure. In the OGC, a similar vote is required within the Planning Committee or as specified
in any Policy and Procedure document used by this committee.
