=== Core Data Dictionary 

[[ConformanceClass-section]]

==== ConformanceClass

set of conformance tests that must be passed to receive a single certificate of conformance (Clause 4.2)
NOTE:  When no ambiguity is possible, the word test may be left out, so conformance test class may be called a conformance class. +
In the ModSpec, the set of requirements tested by the conformance tests within a conformance class is a requirements class and its dependencies. Optional requirements will be in a separate requirements class with other requirements that are part of the same option. Each requirements class corresponds to a separate conformance class +
Each requirements class will be in a 1 to 1 correspondence to a similarly named conformance class that tests all of the requirements in the requirements class. +
All requirements in a conformance class will have the same standardization target type. 

[cols="1a"]
|===
[cols="15,20,5,55",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class* !*multiplicity*  !*Definition*

!{set:cellbgcolor:#FFFFFF}  ! <<ConformanceClass-section,ConformanceClass>> ![1] !
 
!{set:cellbgcolor:#FFFFFF}dependencies  ! <<ConformanceClass-section,ConformanceClass>>  ![0..*] !Conformance classes that this conformance class depends on.  These dependent conformance classes must be passed if this one is to be passed.

!{set:cellbgcolor:#FFFFFF}classes  ! <<ConformanceClass-section,ConformanceClass>> ![1..*] !Conformance classes that this conformance suite contains.
 
!{set:cellbgcolor:#FFFFFF}  ! <<ConformanceSuite-section,ConformanceSuite>>  ![1] !

!{set:cellbgcolor:#FFFFFF}  ! <<ConformanceClass-section,ConformanceClass>> ![1] !
 
!{set:cellbgcolor:#FFFFFF}requirementsClass  ! <<RequirementsClass-section,RequirementsClass>>  ![1] !The requirements class that this conformance class aims to test against.
!===
[cols="15,20,5,55",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type* !*multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} name   !<<String-section,String>> !  !Name of the conformance class
!===
|=== 

[[ConformanceModule-section]]

==== ConformanceModule

a set of related tests within a single conformance test class. A conformance test module is associated with one and only one requirements module 
[ISO 19105] 

NOTE:  When there is no ambiguity, the word test may be omitted, i.e. conformance test module is the same as conformance module. Conformance modules may be nested in a hierarchical way. +
This term and those associated with it are included here for consistency with ISO 19105. 

[cols="1a"]
|===
[cols="15,20,5,55",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class* !*multiplicity*  !*Definition*

!{set:cellbgcolor:#FFFFFF}modules  ! <<ConformanceModule-section,ConformanceModule>> ![1..*] !
 
!{set:cellbgcolor:#FFFFFF}  ! <<ConformanceClass-section,ConformanceClass>>  ![1] !
!===
[cols="15,20,5,55",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type* !*multiplicity* !*Definition*
!===
|=== 

[[ConformanceSuite-section]]

==== ConformanceSuite

set of conformance classes that define tests for all requirements of a standard or abstract specification

NOTE:  The conformance suite is the union of all conformance classes. It is by definition the conformance class of the entire standard or abstract specification. 

In the ModSpec, each requirement is mandatory within its conformance class and each requirement is tested in at least one conformance test. 

[cols="1a"]
|===
[cols="15,20,5,55",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class* !*multiplicity*  !*Definition*

!{set:cellbgcolor:#FFFFFF}testSuite  ! <<ConformanceSuite-section,ConformanceSuite>> ![1] !
 
!{set:cellbgcolor:#FFFFFF}  ! <<Standard-section,Standard>>  ![] !
!===
[cols="15,20,5,55",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type* !*multiplicity* !*Definition*
!===
|=== 

[[ConformanceTest-section]]

==== ConformanceTest

test, abstract or real, of one or more requirements contained within a standard, or set of standards 

[cols="1a"]
|===
[cols="15,20,5,55",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class* !*multiplicity*  !*Definition*

!{set:cellbgcolor:#FFFFFF}tests  ! <<ConformanceTest-section,ConformanceTest>> ![1..*] !Conformance tests that when passed confirm the satisfaction of this requriement. NOTE: If this requirment is a requirement part, it may or may not have a corresponding conformance test.
 
!{set:cellbgcolor:#FFFFFF}  ! <<Requirement-section,Requirement>>  ![1] !

!{set:cellbgcolor:#FFFFFF}test  ! <<ConformanceTest-section,ConformanceTest>> ![1..*] !
 
!{set:cellbgcolor:#FFFFFF}  ! <<ConformanceModule-section,ConformanceModule>>  ![] !
!===
[cols="15,20,5,55",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type* !*multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} abstract   !<<boolean-section,boolean>> !  !Whether this test is abstract or concrete. An abstract conformance test is commonly called an abstract test.
 
!{set:cellbgcolor:#FFFFFF} references   !<<RichText-section,RichText>> !  [0..*] !References to the specification(s) or the conformance test
 
!{set:cellbgcolor:#FFFFFF} testMethod   !<<ConformanceTestMethod-section,ConformanceTestMethod>> !  [0..*] !Method to perform this conformance test. A method is considered a "part" of the test if there are multiple of them.
 
!{set:cellbgcolor:#FFFFFF} testPurpose   !<<String-section,String>> !  !Purpose of the conformance test
 
!{set:cellbgcolor:#FFFFFF} testType   !<<TestType-section,TestType>> !  !Type of the conformance test
!===
|=== 

[[ConformanceTestCase-section]]

==== ConformanceTestCase

test for a particular requirement or a set of related requirements 

NOTE::  When there is no ambiguity, the word case may be omitted. i.e. conformance test is the same as conformance test case. 

[cols="1a"]
|===
[cols="15,20,5,55",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class* !*multiplicity*  !*Definition*
!===
[cols="15,20,5,55",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type* !*multiplicity* !*Definition*
!===
|=== 

[[ConformanceTestMethod-section]]

==== ConformanceTestMethod



[cols="1a"]
|===
[cols="15,20,5,55",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class* !*multiplicity*  !*Definition*
!===
[cols="15,20,5,55",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type* !*multiplicity* !*Definition*
!===
|=== 

[[CoreRequirementsClass-section]]

==== CoreRequirementsClass

unique requirements class that must be satisfied by any conformant standardization targets associated to the standard

NOTE:  The core requirements class is unique because if it was possible to have more than one, then each core would have to be implemented to pass any conformance test class, and thus would have to be contained in any other core. The core may be empty, or all or part of another standard or related set of standards. 

The core can refer to this requirements class, its associated conformance test class or the software module that implements that requirements class. 

[cols="1a"]
|===
[cols="15,20,5,55",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class* !*multiplicity*  !*Definition*
!===
[cols="15,20,5,55",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type* !*multiplicity* !*Definition*
!===
|=== 

[[GeneralRecommendation-section]]

==== GeneralRecommendation

recommendation applying to all entities in a specification model 

[cols="1a"]
|===
[cols="15,20,5,55",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class* !*multiplicity*  !*Definition*
!===
[cols="15,20,5,55",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type* !*multiplicity* !*Definition*
!===
|=== 

[[InformativeStatement-section]]

==== InformativeStatement

expression in a document conveying non-normative information

NOTE::  Includes all statements in a document not part of the normative requirements, recommendations, permissions, or conformance tests. Included for completeness.

[cols="1a"]
|===
[cols="15,20,5,55",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class* !*multiplicity*  !*Definition*

!{set:cellbgcolor:#FFFFFF}  ! <<InformativeStatement-section,InformativeStatement>> ![] !
 
!{set:cellbgcolor:#FFFFFF}  ! <<Specification-section,Specification>>  ![] !
!===
[cols="15,20,5,55",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type* !*multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} name   !<<String-section,String>> !  !
!===
|=== 

[[Model-section]]

==== Model

A representation of those aspects of the standardization target type which are to be governed by a standard. The model captures both the conceptual and logical properties of the standardization target type. The requirements promulgated by a standard should be expressed in terms of those conceptual and logical properties.

In short, the model provides the vocabulary for expressing requirements.

[cols="1a"]
|===
[cols="15,20,5,55",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class* !*multiplicity*  !*Definition*
!===
[cols="15,20,5,55",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type* !*multiplicity* !*Definition*
!===
|=== 

[[Module-section]]

==== Module

each of a set of standardized parts or independent units that can be used to construct a more complex structure.

NOTE:  The concept `module` is key to the ModSpec structure and model. Modules have a direct relationship to the concept of building blocks. The power of the concept is that modules can be reused in different systems (specify once, use many). MOdules can be imported from other programs. Modules can be replaced without affecting the rest of the system.

[cols="1a"]
|===
[cols="15,20,5,55",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class* !*multiplicity*  !*Definition*
!===
[cols="15,20,5,55",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type* !*multiplicity* !*Definition*
!===
|=== 

[[NormativeStatement-section]]

==== NormativeStatement

expression in a document conveying information required to define conformance

NOTE:  Includes all normative statements in a document including requirements, recommendations, permissions, and conformance tests. Included for completeness.

[cols="1a"]
|===
[cols="15,20,5,55",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class* !*multiplicity*  !*Definition*

!{set:cellbgcolor:#FFFFFF}  ! <<NormativeStatement-section,NormativeStatement>> ![] !
 
!{set:cellbgcolor:#FFFFFF}  ! <<Specification-section,Specification>>  ![] !
!===
[cols="15,20,5,55",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type* !*multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} name   !<<String-section,String>> !  !Name of the normative statement
!===
|=== 

[[Permission-section]]

==== Permission

uses “may” and is used to prevent a requirement from being “over interpreted” and as such is considered to be more of a “statement of fact” than a “normative” condition.

[cols="1a"]
|===
[cols="15,20,5,55",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class* !*multiplicity*  !*Definition*

!{set:cellbgcolor:#FFFFFF}  ! <<Permission-section,Permission>> ![] !
 
!{set:cellbgcolor:#FFFFFF}  ! <<RequirementsModule-section,RequirementsModule>>  ![] !
!===
[cols="15,20,5,55",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type* !*multiplicity* !*Definition*
!===
|=== 

[[Principal-section]]

==== Principal



[cols="1a"]
|===
[cols="15,20,5,55",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class* !*multiplicity*  !*Definition*
!===
[cols="15,20,5,55",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type* !*multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} contactInformation   !<<String-section,String>> !  [1..*] !
 
!{set:cellbgcolor:#FFFFFF} name   !<<String-section,String>> !  !
!===
|=== 

[[Recommendation-section]]

==== Recommendation

expression in the content of a standard conveying that among several possibilities one is recommended as particularly suitable, without mentioning or excluding others, or that a certain course of action is preferred but not necessarily required, or that (in the negative form) a certain possibility or course of action is deprecated but not prohibited 

NOTE:  Although using normative language, a recommendation is not a requirement. The usual form replaces the shall (imperative or command) of a requirement with a should (suggestive or conditional). 

NOTE:  Recommendations are not tested and therefore have no related conformance test.

[ISO Directives Part 2]

[cols="1a"]
|===
[cols="15,20,5,55",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class* !*multiplicity*  !*Definition*
!===
[cols="15,20,5,55",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type* !*multiplicity* !*Definition*
!===
|=== 

[[Requirement-section]]

==== Requirement

expression in the content of a standard conveying criteria to be fulfilled if compliance with the standard is to be claimed and from which no deviation is permitted
[ISO Directives Part 2] 

NOTE:  Each requirement is a normative criterion for a single type of standardization target. In the ModSpec, requirements are associated to conformance tests that can be used to prove compliance to the underlying criteria by the standardization target. 

The implementation of a requirement is dependent on the type of standard being written. A data standard requires data structures, but a procedural standard requires software implementations. The view of a standard in terms of a set of testable requirements allows us to use set descriptions of both the standard and its implementations.

The specification of a requirement is usually expressed in terms of a model of the standardization target type, such as a UML model, or an XML or SQL schema. Anything without a defined test is a-priori not testable and thus would be better expressed as a recommendation. 

Requirements use normative language and in particular are commands and use the imperative "shall" or similar imperative constructs. Statements in standards which are not requirements and need to be either conditional or future tense normally use "will" and should not be confused with requirements that use "shall" imperatively 

[cols="1a"]
|===
[cols="15,20,5,55",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class* !*multiplicity*  !*Definition*

!{set:cellbgcolor:#FFFFFF}parts  ! <<Requirement-section,Requirement>> ![0..*] !Collection of requirements that are parts to this requirement. Satisfaction of all requirement parts are necessary for this requirement to be satisfied.
 
!{set:cellbgcolor:#FFFFFF}  ! <<Requirement-section,Requirement>>  ![] !

!{set:cellbgcolor:#FFFFFF}requirements  ! <<Requirement-section,Requirement>> ![1..*] !Requirements classes, recommendations, and permissions that this requirements module contains.
 
!{set:cellbgcolor:#FFFFFF}  ! <<RequirementsModule-section,RequirementsModule>>  ![] !

!{set:cellbgcolor:#FFFFFF}requirements  ! <<Requirement-section,Requirement>> ![1..*] !Corresponding requirement of requirement part that this conformance test is supposed to test against.
 
!{set:cellbgcolor:#FFFFFF}  ! <<ConformanceTest-section,ConformanceTest>>  ![1] !
!===
[cols="15,20,5,55",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type* !*multiplicity* !*Definition*
!===
|=== 

[[RequirementsClass-section]]

==== RequirementsClass

aggregate of all requirements (Clause 4.21) for a single standardization target that must all be satisfied to pass a conformance test Class

NOTE:  There is some confusion possible here, since the testing of indirect dependencies seems to violate this definition. But the existence of an indirect dependency implies that the test is actually a test of the existence of the relationship from the original target to something that has a property (satisfies a condition or requirement from another requirements class). 

[cols="1a"]
|===
[cols="15,20,5,55",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class* !*multiplicity*  !*Definition*

!{set:cellbgcolor:#FFFFFF}classes  ! <<RequirementsClass-section,RequirementsClass>> ![1..*] !
 
!{set:cellbgcolor:#FFFFFF}  ! <<Standard-section,Standard>>  ![] !

!{set:cellbgcolor:#FFFFFF}dependencies  ! <<RequirementsClass-section,RequirementsClass>> ![0..*] !Requirements classes that this requirements class depends on. These dependend reuqirments classes must be satisfied for this requirements class to be satisfied.
 
!{set:cellbgcolor:#FFFFFF}  ! <<RequirementsClass-section,RequirementsClass>>  ![] !
!===
[cols="15,20,5,55",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type* !*multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} name   !<<String-section,String>> !  !Name of the requirements class
!===
|=== 

[[RequirementsModule-section]]

==== RequirementsModule

a set of related requirements (Clause 4.22), recommendations (Clause 4.20) and permissions (Clause 4.18) within a single requirements class (Clause 4.26)

NOTE::  This term is included to be consistent with the use of modules in ISO 19105. 

[cols="1a"]
|===
[cols="15,20,5,55",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class* !*multiplicity*  !*Definition*

!{set:cellbgcolor:#FFFFFF}modules  ! <<RequirementsModule-section,RequirementsModule>> ![1..*] !A set of one or more requirments classes, recommendations, and permissions with the same standardization target.
 
!{set:cellbgcolor:#FFFFFF}  ! <<RequirementsClass-section,RequirementsClass>>  ![] !
!===
[cols="15,20,5,55",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type* !*multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} name   !<<String-section,String>> !  !Name of the requirements module
!===
|=== 

[[Specification-section]]

==== Specification

document containing recommendations, requirements, permissions, and conformance tests

NOTE:  This definition is included for completeness. 

NOTE:  In the OGC, there are Abstract Specifications and Implementation Standards. Abstract Specifications may of may not be testable. Further, Abstract Specifications may not be directly implementable. Implementation Standards are always testable and contain a conformance test suite.

[cols="1a"]
|===
[cols="15,20,5,55",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class* !*multiplicity*  !*Definition*
!===
[cols="15,20,5,55",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type* !*multiplicity* !*Definition*
!===
|=== 

[[Standard-section]]

==== Standard

a specification that has been approved by a legitimate Standards Body 

NOTE::  This definition is included for completeness. Standard and specification can apply to the same document. While specification is always valid, standard only applies after the adoption of the document by a legitimate standards organization.  

[cols="1a"]
|===
[cols="15,20,5,55",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class* !*multiplicity*  !*Definition*

!{set:cellbgcolor:#FFFFFF}references  ! <<Standard-section,Standard>> ![0..*] !
 
!{set:cellbgcolor:#FFFFFF}  ! <<Standard-section,Standard>>  ![] !
!===
[cols="15,20,5,55",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type* !*multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} authority   !<<Principal-section,Principal>> !  !Standards body or author of this standard
 
!{set:cellbgcolor:#FFFFFF} date   !<<DateTime-section,DateTime>> !  !Publication date of the standard
 
!{set:cellbgcolor:#FFFFFF} name   !<<String-section,String>> !  !Name of the standard
 
!{set:cellbgcolor:#FFFFFF} status   !<<String-section,String>> !  !Publication status of this standard
!===
|=== 

[[StandardizationTarget-section]]

==== StandardizationTarget

entity to which some requirements of a standard apply 
NOTE::   The standardization target is the entity which may receive a certificate of conformance for a requirements class. 

[cols="1a"]
|===
[cols="15,20,5,55",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class* !*multiplicity*  !*Definition*
!===
[cols="15,20,5,55",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type* !*multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} conformanceCertificates   !<<String-section,String>> !  [0..*] !Conformance classes passed by this target
!===
|=== 

[[StandardizationTargetType-section]]

==== StandardizationTargetType

type of entity or set of entities to which the requirement (Clause 4.21) of a standard (Clause 4.25) apply

NOTE:  For example, the standardization target type for The OGC API – Features Standard are Web APIs. The standardization target type for the CDB Standard is “datastore”. It is important to understand that a standard’s root standardization target type can have sub-types, and that there can be a hierarchy of target types. For example, a Web API can have sub types of client, server, security, and so forth. As such, each requirements class can have a standardization target type that is a sub-type of the root.

[cols="1a"]
|===
[cols="15,20,5,55",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class* !*multiplicity*  !*Definition*

!{set:cellbgcolor:#FFFFFF}targetType  ! <<StandardizationTargetType-section,StandardizationTargetType>> ![1] !Type of standardization target
 
!{set:cellbgcolor:#FFFFFF}  ! <<RequirementsClass-section,RequirementsClass>>  ![0..*] !

!{set:cellbgcolor:#FFFFFF}Type  ! <<StandardizationTargetType-section,StandardizationTargetType>> ![] !Type of the standardization target type
 
!{set:cellbgcolor:#FFFFFF}  ! <<StandardizationTarget-section,StandardizationTarget>>  ![] !
!===
[cols="15,20,5,55",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type* !*multiplicity* !*Definition*
!===
|=== 

[[Statement-section]]

==== Statement

Original

expression in a document conveying information 
[ISO Directives Part 2] 

NOTE::  Includes all statements in a document not part of the normative requirements, recommendations or conformance tests. Included for completeness. 

[cols="1a"]
|===
[cols="15,20,5,55",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class* !*multiplicity*  !*Definition*
!===
[cols="15,20,5,55",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type* !*multiplicity* !*Definition*
!===
|=== 

[[TestType-section]]

==== TestType



[cols="1a"]
|===
[cols="15,20,5,55",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class* !*multiplicity*  !*Definition*
!===
[cols="15,20,5,55",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type* !*multiplicity* !*Definition*
 
!{set:cellbgcolor:#FFFFFF} basic «enum»  !<<-section,>> !  !
 
!{set:cellbgcolor:#FFFFFF} capabilities «enum»  !<<-section,>> !  !
!===
|=== 

=== Concepts Data Dictionary 

[[CertificateOfConformance-section]]

==== CertificateOfConformance

evidence of conformance to all or part of a standard, awarded for passing one or more of the conformance test classes specified in that standard 

NOTE:  Certificates‖ do not have to be instantiated documents; having proof of passing the conformance test class is sufficient. For example, the OGC currently keeps an online list of conformant applications at http://www.opengeospatial.org/resource/products. 
Each certificate of conformance is awarded to a standardization target. 

[cols="1a"]
|===
[cols="15,20,5,55",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class* !*multiplicity*  !*Definition*
!===
[cols="15,20,5,55",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type* !*multiplicity* !*Definition*
!===
|=== 

[[DirectDependency-section]]

==== DirectDependency

Original

another requirements class (the dependency) whose requirements are defined to also be requirements of this requirements class

NOTE: A direct dependency (of a requirements class) of the current requirements class will have the same standardization target as the current requirements class. This is another ways of saying that the current requirements class extends, or uses all the aspects of the direct dependency (or a requirements class). Any tests associated to this dependency can be applied to this requirements class. 

When testing a direct dependency of a requirements class, the standardization target is directly subject to the test in the specified conformance test class of the direct dependency of a requirements class. 

[cols="1a"]
|===
[cols="15,20,5,55",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class* !*multiplicity*  !*Definition*
!===
[cols="15,20,5,55",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type* !*multiplicity* !*Definition*
!===
|=== 

[[Extension-section]]

==== Extension

requirements class which has a direct dependency on another requirements class 

NOTE:: Here an extension of a requirements class is defined on requirements class so that their implementation may be software extensions in a manner analogous to the extension relation between the requirements classes. 

[cols="1a"]
|===
[cols="15,20,5,55",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class* !*multiplicity*  !*Definition*
!===
[cols="15,20,5,55",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type* !*multiplicity* !*Definition*
!===
|=== 

[[Home-section]]

==== Home

official statement of a requirement or recommendation that is the precedent for any other version repeated or rephrased elsewhere 

NOTE:: Explanatory text associated to normative language often repeats or rephrases the requirement to aid in the discussion and understanding of the official version of the normative language. Since such restatements are often less formal than the original source and potentially subject to alternate interpretation, it is important to know the location of the home official version of the language. 

[cols="1a"]
|===
[cols="15,20,5,55",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class* !*multiplicity*  !*Definition*
!===
[cols="15,20,5,55",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type* !*multiplicity* !*Definition*
!===
|=== 

[[IndirectDependency-section]]

==== IndirectDependency

requirements class with a different standardization target which is used, produced or associated to by the implementation of this requirements class 

NOTE: In this instance, as opposed to the direct dependency of a requirements class, the test against the consumable or product used or produced by the requirements class does not directly test the requirements class, but tests only its side effects. Hence, a particular type of feature service could be required to produce valid XML documents, but the test of validity for the XML document is not directly testing the service, but only indirectly testing the validity of its output. Direct dependencies test the same standardization target, but indirect dependencies test related but different standardization targets. +
For example, if a DRM-enabled service is required to have an association to a licensing service, then the requirements of a licensing service are indirect requirements for the DRM-enabled service. Such a requirement may be stated as the associated licensing service has a certificate of conformance of a particular kind. 

[cols="1a"]
|===
[cols="15,20,5,55",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class* !*multiplicity*  !*Definition*
!===
[cols="15,20,5,55",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type* !*multiplicity* !*Definition*
!===
|=== 

[[LeafPackage-section]]

==== LeafPackage

Original

UML model package that does not contain any subpackages, but contains classifiers 
[UML] 

[cols="1a"]
|===
[cols="15,20,5,55",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class* !*multiplicity*  !*Definition*
!===
[cols="15,20,5,55",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type* !*multiplicity* !*Definition*
!===
|=== 

[[Profile-section]]

==== Profile

specification or standard consisting of a set of references to one or more base standards and/or other profiles, and the identification of any chosen conformance test classes, conforming subsets, options and parameters of those base standards, or profiles necessary to accomplish a particular function. 

NOTE:  In the usage of the ModSpec, a profile will be a set of requirements classes or conformance classes (either preexisting or locally defined) of the base standards.

This means that a standardization target being conformant to a profile implies that the same target is conformant to the standards referenced in the profile.

[ISO/IEC TR 10000-1] 

[cols="1a"]
|===
[cols="15,20,5,55",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class* !*multiplicity*  !*Definition*
!===
[cols="15,20,5,55",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type* !*multiplicity* !*Definition*
!===
|===   

=== Types Data Dictionary 

[[DateTime-section]]

==== DateTime



[cols="1a"]
|===
[cols="15,20,5,55",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class* !*multiplicity*  !*Definition*
!===
[cols="15,20,5,55",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type* !*multiplicity* !*Definition*
!===
|=== 

[[RichText-section]]

==== RichText



[cols="1a"]
|===
[cols="15,20,5,55",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class* !*multiplicity*  !*Definition*
!===
[cols="15,20,5,55",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type* !*multiplicity* !*Definition*
!===
|=== 

[[String-section]]

==== String



[cols="1a"]
|===
[cols="15,20,5,55",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Role name* !*Target class* !*multiplicity*  !*Definition*
!===
[cols="15,20,5,55",frame=none,grid=none,options="header"]
!===
!{set:cellbgcolor:#DDDDDD} *Attribute* !*Value type* !*multiplicity* !*Definition*
!===
|===     



