=== Core Terms and Definitions

[[ConformanceClass-definition]]

==== ConformanceClass

set of conformance tests that must be passed to receive a single certificate of conformance (Clause 4.2)
NOTE:: When no ambiguity is possible, the word test may be left out, so conformance test class may be called a conformance class. +
In the ModSpec, the set of requirements tested by the conformance tests within a conformance class is a requirements class and its dependencies. Optional requirements will be in a separate requirements class with other requirements that are part of the same option. Each requirements class corresponds to a separate conformance class +
Each requirements class will be in a 1 to 1 correspondence to a similarly named conformance class that tests all of the requirements class’s requirements. +
All requirements in a conformance class will have the same standardization target type.  

[[ConformanceModule-definition]]

==== ConformanceModule

a set of related tests, all within a single conformance test class 
[ISO 19105] 

NOTE:: When there is no ambiguity, the word test may be omitted, i.e. conformance test module is the same as conformance module. Conformance modules may be nested in a hierarchical way. +
This term and those associated with it are included here for consistency with ISO 19105.  

[[ConformanceSuite-definition]]

==== ConformanceSuite

set of conformance classes that define tests for all requirements of a standard or abstract specification

NOTE:: The conformance suite is the union of all conformance classes. It is by definition the conformance class of the entire specification. 

In this standard, each requirement is mandatory within its conformance class and each requirement is tested in at least one conformance test.  

[[ConformanceTest-definition]]

==== ConformanceTest

test, abstract or real, of one or more requirements contained within a standard, or set of standards  

[[ConformanceTestCase-definition]]

==== ConformanceTestCase

test for a particular requirement or a set of related requirements 

NOTE:: When there is no ambiguity, the word case may be omitted. i.e. conformance test is the same as conformance test case.  

[[ConformanceTestMethod-definition]]

==== ConformanceTestMethod

 

[[CoreRequirementsClass-definition]]

==== CoreRequirementsClass

Original

unique requirements class that must be satisfied by any conformant standardization targets associated to the specification 

NOTE:: The core requirements class is unique because if it was possible to have more than one, then each core would have to be implemented to pass any conformance test class, and thus would have to be contained in any other core. The core may be empty, or all or part of another standard or related set of standards. 

The core can refer to this requirements class, its associated conformance test class or the software module that implements that requirements class.  

[[GeneralRecommendation-definition]]

==== GeneralRecommendation

Original

recommendation applying to all entities in a specification model  

[[InformativeStatement-definition]]

==== InformativeStatement

expression in a document conveying information

NOTE: Includes all statements in a document not part of the normative requirements, recommendations, or conformance tests. Included for completeness. 

[[NormativeStatement-definition]]

==== NormativeStatement

expression in a document conveying information

NOTE: Includes all statements in a document not part of the normative requirements, recommendations, or conformance tests. Included for completeness. 

[[Permission-definition]]

==== Permission

uses “may” and is used to prevent a requirement from being “over interpreted” and as such is considered to be more of a “statement of fact” than a “normative” condition. 

[[Principal-definition]]

==== Principal

 

[[Recommendation-definition]]

==== Recommendation

expression in the content of a standard conveying that among several possibilities one is recommended as particularly suitable, without mentioning or excluding others, or that a certain course of action is preferred but not necessarily required, or that (in the negative form) a certain possibility or course of action is deprecated but not prohibited 
[ISO Directives Part 2]

NOTE:: Although using normative language, a recommendation is not a requirement. The usual form replaces the shall (imperative or command) of a requirement with a should (suggestive or conditional).  

[[Requirement-definition]]

==== Requirement

expression in the content of a standard conveying criteria to be fulfilled if compliance with the standard is to be claimed and from which no deviation is permitted
[ISO Directives Part 2] 

NOTE:: Each requirement is a normative criterion for a single standardization target type. In this standard, requirements will be associated to conformance tests that can be used to prove compliance to the underlying criteria by the standardization target. 

The implementation of a requirement is dependent on the type of specification being written. A data specification requires data structures, but a procedural specification requires software implementations. The view of a standard in terms of a set of testable requirements allows us to use set descriptions of both the standard and its implementations.

The specification of a requirement is usually expressed in terms of a model of the standardization target type, such as a UML model, or an XML or SQL schema. Anything without a defined test is a priori not testable and thus would be better expressed as a recommendation. 

Requirements use normative language and in particular are commands and use the imperative shall or similar imperative constructs. Statements in standards which are not requirements and need to be either conditional or future tense normally use will and should not be confused with requirements that use shall imperatively  

[[RequirementsClass-definition]]

==== RequirementsClass

aggregate of all requirements (Clause 4.21) that must all be satisfied to satisfy a conformance test Class

NOTE:: There is some confusion possible here, since the testing of indirect dependencies seems to violate this definition. But the existence of an indirect dependency implies that the test is actually a test of the existence of the relationship from the original target to something that has a property (satisfies a condition or requirement from another requirements class).  

[[RequirementsModule-definition]]

==== RequirementsModule

a set of related requirements (Clause 4.22), recommendations (Clause 4.20) and permissions (Clause 4.18) all with a single requirements class (Clause 4.26)

NOTE:: This term is included to be consistent with the use of modules in ISO 19105.  

[[Specification-definition]]

==== Specification

document containing recommendations, requirements and conformance tests for those requirements 

NOTE:: This definition is included for completeness. See Clause 5.3. This does not restrict what else a specification may contain, as long as it does contain the three types of element cited.  

[[Standard-definition]]

==== Standard

document containing recommendations (Clause 4.20), requirements (Clause 4.21) and conformance tests (Clause 4.6) that has been approved by a legitimate Standards Body

(original) specification that has been approved by a legitimate Standards Body 

NOTE:: This definition is included for completeness. Standard and specification can apply to the same document. While specification is always valid, standard only applies after the adoption of the document by a legitimate standards organization.  The legitimate Standards Bodies for OGC consist of OGC, ISO and any of the other standards bodies accepted and used as a source of normative references by OGC or ISO in their standards. In the normal meaning of the word standard, there are other conditions that may be required, but this standard has chosen to ignore them in the process of abstraction.  

[[StandardizationTarget-definition]]

==== StandardizationTarget

entity to which some requirements of a standard apply 
NOTE The standardization target is the entity which may receive a certificate of conformance for a requirements class.  

[[StandardizationTargetType-definition]]

==== StandardizationTargetType

type of entity or set of entities to which the requirement (Clause 4.21) of a standard (Clause 4.25) apply

NOTE:: The standardization target types give the standardization targets a typing system similar to the UML classifiers. In general, the types inherit from one another in the same way that UML classes do. The same class/metaclass semantics apply, and two targets can be considered to have the same type (in a particular situation) if their instantiation types share the appropriate supertype, as is the case in UML. In OGC for example, all service types that must pass the OWS (Open Web Services) Common specification are some extension of the Open Web Service standardization target type. This makes OWS Common a default global core for all OGC Services. 

In some cases, the standardization target type may be another specification. A GML application schema is a standardization target for the GML standard, but is in turn a specification of instances of that application schema.  

[[Statement-definition]]

==== Statement

Original

expression in a document conveying information 
[ISO Directives Part 2] 

NOTE:: Includes all statements in a document not part of the normative requirements, recommendations or conformance tests. Included for completeness.  

[[TestType-definition]]

==== TestType

 

=== Concepts Terms and Definitions

[[CertificateOfConformance-definition]]

==== CertificateOfConformance

evidence of conformance to all or part of a standard, awarded for passing one or more of the conformance test classes specified in that standard 

NOTE:: Certificates‖ do not have to be instantiated documents; having proof of passing the conformance test class is sufficient. For example, the OGC currently keeps an online list of conformant applications at http://www.opengeospatial.org/resource/products. 
Each certificate of conformance is awarded to a standardization target.  

[[DirectDependency-definition]]

==== DirectDependency

Original

another requirements class (the dependency) whose requirements are defined to also be requirements of this requirements class

NOTE:: A direct dependency of the current requirements class will have the same standardization target as the current requirements class. This is another ways of saying that the current requirements class extends, or uses all the aspects of the direct dependency. Any tests associated to this dependency can be applied to this requirements class. 

When testing a direct dependency, the standardization target is directly subject to the test in the specified conformance test class of the direct dependency.  

[[Extension-definition]]

==== Extension

Original
requirements class which has a direct dependency on another requirements class 

NOTE:: Here extension is defined on requirements class so that their implementation may be software extensions in a manner analogous to the extension relation between the requirements classes.  

[[Home-definition]]

==== Home

Original

official statement of a requirement or recommendation that is the precedent for any other version repeated or rephrased elsewhere 

NOTE:: Explanatory text associated to normative language often repeats or rephrases the requirement to aid in the discussion and understanding of the official version of the normative language. Since such restatements are often less formal than the original source and potentially subject to alternate interpretation, it is important to know the location of the home official version of the language. 
These alternative statements use non-normative language and are statements using the definitions of the ISO Directives Part 2.  

[[IndirectDependency-definition]]

==== IndirectDependency

Original

requirements class with a different standardization target which is used, produced or associated to by the implementation of this requirements class 

NOTE:: In this instance, as opposed to the direct dependency, the test against the consumable or product used or produced by the requirements class does not directly test the requirements class, but tests only its side effects. Hence, a particular type of feature service could be required to produce valid XML documents, but the test of validity for the XML document is not directly testing the service, but only indirectly testing 

the validity of its output. Direct dependencies test the same standardization target, but indirect dependencies test related but different standardization targets. 
The standardization target of the indirect dependency is different from the target of ―this requirements class‖ but it may be of the same or related standardization target type. For example, if one service is related to another second service, then a service requirement may be placed against the second associated service to assure that the first service has access to its functionality. For example, if a DRM-enabled service is required to have an association to a licensing service, then the requirements of a licensing service are indirect requirements for the DRM-enabled service. Such a requirement may be stated as the associated licensing service has a certificate of conformance of a particular kind.  

[[LeafPackage-definition]]

==== LeafPackage

Original

UML model package that does not contain any subpackages, but contains classifiers 
[UML]  

[[Model-definition]]

==== Model

Original

theoretical construct that represents something, with a set of variables and a set of logical and quantitative relationships between them.

NOTE Derived from Wikipedia 

The "theoretical construct" is essentially a conceptual metaphor with the target of the metaphor as the thing being modeled, and the source of the metaphor as the model. The terms are almost interchangeable, with model being preferred when the source is a constructed entity, and metaphor being preferred when the source already exists, and the emphasis is the mapping between it and the target. 

The definition in ISO 19101, Clause 4.4 is conceptual model - model that defines concepts of a universe of discourse. 
While adequate in the context of a ―universe of discourse‖ as the something addressed by a standard, a model need not have any ―universality‖ property at all. Most often models are representative of only a relatively small portion of a larger universe, and part of the process of modeling is to factor out the 
properties and things to which no interest is directed within the present standard It also fails to define ―model‖ which is in fact the central issue within this discussion. 
The abstract or conceptual is actually redundant and will often be dropped in the text. Models are by their vary nature not the same as what they are describing, and thus must contain a conceptual metaphor to describe their relationship to the target (the thing being described) of the model. This inherently makes them abstractions.  

[[Profile-definition]]

==== Profile

Original

specification or standard consisting of a set of references to one or more base standards and/or other profiles, and the identification of any chosen conformance test classes, conforming subsets, options and parameters of those base standards, or profiles necessary to accomplish a particular function. 

[ISO/IEC TR 10000-1] 

NOTE:: This definition has been adopted from ISO 10000: Part 1. The wording has been changed to accommodate the shared vocabulary of OGC and ISO TC 211 and for editorial reasons. The original text is ―A set of one or more base standards and/or ISPs, and, where applicable, the identification of chosen classes, conforming subsets, options and parameters of those base standards, or ISPs necessary to accomplish a particular function.‖ 
In the usage of this standard, a profile will be a set of requirements classes or conformance classes (either preexisting or locally defined) of the base standards. 
This means that a standardization target being conformant to a profile implies that the same target is conformant to the standards referenced in the profile.    

=== Types Terms and Definitions

[[RichText-definition]]

==== RichText

 

[[DateTime-definition]]

==== DateTime

 

[[String-definition]]

==== String

     


