[.preface]
== Abstract

This OGC ModSpec Policy specifies requirements and guidance for using the OGC ModSpec as the formal structure for all OGC standards documents. This OGC member Policy mandates using the ModSpec model and related requirements and recommendations for writing and structuring modular OGC standards Further, this Policy mandates that every OGC Implementation Standard will provide an Abstract Test Suite (conformance suite)  designed to enable the consistent and verifiable testing of implementations of an OGC Standard that claim conformance.

For OGC Standards work, the word “standard” in the ModSpec applies to all OGC draft standards, approved standards, draft Abstract Specifications, and approved Abstract Specifications. The exceptions are OGC Abstract Specifications that originate in ISO or Community Standards that are developed external to the OGC and then submitted to the OGC.

The goal of this Policy is to ensure that a standard specifies requirements in a common and consistent manner and that these requirements are testable.

Suggested additions, changes, and comments on this this document are welcome and
encouraged. Such suggestions may be submitted through the OGC Change Request System
(http://www.opengeospatial.org/standards/cr) or by creating an issue in the GitHub repository for this document (https://github.com/opengeospatial/ogc-modspec).

[.preface]
== Document editors

The following OGC Members participated in editing this document:

[%unnumbered]
|===
^h| Person ^h| Organization Represented
| Carl Reed | Carl Reed & Associates
|===

[.preface]
== Document Contributors

The following OGC Members contributed and particpated in developing Version 2 of the ModSpec.

[%unnumbered]
|===
^h| Person ^h| Organization Represented
| Chuck Heazel | Heazeltech
| Jeff Yutzler | ImageMatters
|===
