[[modspec-policy]]
== ModSpec Policy Requirements

The following states requirements for the use of the ModSpec in OGC Standards development work and for structuring OGC Standards documents.

The following states that for any OGC Standards development, the ModSpec model will be used.

- Any new OGC Standard, revision to an existing OGC Standard, new abstract specification that has requirements, or revision to an existing abstract specification that has requirements _SHALL_ comply with the requirements stated in the OGC ModSpec Core Standard and relevant Parts.

Any OGC Standards document must specify a standardization goal.

- Any new OGC Standard, abstract specification containing requirements, or major revision of an existing OGC Standard _SHALL_ clearly state the standardization goal for the standard or abstract specification. This statement _SHOULD_ be in the `Abstract` or `Scope` clauses of the standard. Please note that a Standard's stated goal drove the original development of the standard. However, other uses of a standard or elements of the standard are not precluded.

OGC Standards documents must be written using an official OGC template

- All OGC Standards documents _SHALL_ be written using the OGC Member approved template. This document template _SHALL_ be conformant with the requirements stated in the ModSpec

All OGC Implementation Standards must have an Abstract Test Suite. Please note that in the ModSpec, the correct terminology is Conformance Test Suite. However, to be consistent with OGC usage over the last 15 years and to be consistent with the template, the term used is Abstract Test Suite.

- All OGC Implementation Standards documents _SHALL_ have an Abstract Test Suite (Conformance Test Suite) document in Annex A of the standards document. This Annex _SHALL_ be designated as `normative`



