[[Clause_Critical]]
== Description of critical changes

There are four (3) critical changes in the ModSpec: Core Standard. None of these chnages affect backwards compatibility.

=== Critcal Change 1: ModSpec 1.1 is not OGC Policy. 

The decision was made to not have the OGC ModSpec: Core as an OGC Policy Document. The reason is that the ModSpec should be useable by and Standards organization and not just the OGC. Instead:

- The ModSpec document itself is now an OGC Standard.
- A separate document titled, https://portal.ogc.org/files/?artifact_id=110275&version=1[The ModSpec Model: OGC Policy] was developed. This Policy will be reviewed, discussed, and approved as an OGC Policy document

The impact was to modify the ModSpec 1.1 document to remove all references to the ModSpec being a Policy document. Most of the time the word `Policy` was changed to `Standard` or `standard`.

This is GitHub issue 9 and 37.

=== Critical Change 2: ModSpec 1.1: Core and Parts

To be consistent with itself, the ModSpec was restructured into a core and two Parts:

- Core: contains all the core requirements and informational text that define the model and internal structure of a standard.
- Part 1: UML Model requirements 
- Part 2: XML and Schematron Model requirements 

This is GitHub issue 36.

=== Critical Change 3: ModSpec Permissions and Recommendations clearly identified

In the ModSpec version 1.0, permissions and recommendations were embedded in the general text and were not specifically highlighted. Further. the concept permission was not defined. In the ModSpec version 1.1, the concept `permission` is defined. Further, all permissions and recommendation are extracted from the general text and placed in tablesas per the Metanorma template. Further, all permissions and recommendations are bookmarked for easier navigation.

This is GitHub issue 34.

=== Critical Change 4: Clarification and consistent use of `specification` and `standard`

In the ModSpec Version 1.0 there is a short paragraph:

`In this standard, other documents which may be standards but are being tested for conformance to this standard are referred to as “specifications.” The purpose of this linguistic artifact is to prevent confusion between this standard and the standardization targets of its requirements.`

There were two maun issues with this statement:

- The statement is confusing and to an extent artificial;
- This "artifact" was not consistently applied in Version 1. The editors went back and forth and often, despite the rule, intermixed the terms causes confusion.

In Version 1.1 of the ModSpec, by no longer referring to the ModSpec as a Policy, we can instead refer to the ModSpec as Standard for writing modular standards. Further, we can reference documents that will become standards as standards or draft standard. Finally, the ModSpec document itself is refered to as the ModSpec and not a policy or standard.

This change, applied to the entire document, removes the ambiguity. The change was applied consistently throughout Version 1.1. 

This is GitHub issue 10.

=== Critical Change 5: What is a Requirements Module?

In the ModSpec Version 1.0 there is a logical inconsistency related to the definitions, relationship, and modelling of requirements modules and requirements classes. In Version 1.0, a Requirements Class can be composed of one or more Requirements Modules and one or more Recommendations. However, multiple locations in the Vesion 1.0 document state that recommendations are not testable (Old Section 6.1 for example). This create a logical inconsistency as a Requirements Class is composed of requirements and recommendations but the wording of the conformance test class states that in order to be conformant that all elements of a requirements class must pass - but recommendations cannot be tested.

So, given that most OGC Standards do not use Requirements Modules, then a straightforward solution is to swap Requirements Modules and Requirements classes in the hierarchy. As such, then a Requirements Module would consist of Requirements Classes, Recommendations, and Permissions. A Requirements Class would have no recommendations. Therefore, a Requirements Class would be testable.

NOTE: CDB 2.0 does define Requirements Modules but based on the above proposed definition.
