== Introduction

=== Scope

The ModSpec Core Standard defines characteristics and structure for the specification of Standards that will encourage implementation by minimizing difficulty determining requirements, mimicking implementation structure, and maximizing usability and interoperability.

Part 1 of the ModSpec defines the requirements for using UML. The use case is if the organizing mechanism for the data model used in a standard is an object model, then the mapping from parts of the model to the requirements classes should follow the logical mechanism described in Part 1 of the ModSpec.

Part 2 of the ModSpec defines the requirements for using XML. The XML related requirements classes cover any standard which has as one of its purposes the introduction of a new XML schema. Such a standard would normally define the schema, all of its components, and its intended uses.

=== Document contributor contact points

All questions regarding this document should be directed to the contacts provided below or the referenced standard editor(s).

.Contacts
[width="80%",options="header"]
|====================
|Name |Organization
|Carl Reed | Carl Reed
|Jeff Yutzler |Tepa / Image Matters
|====================
