[[cls-6]]
== Requirements Class: Part 2 UML

This clause defines the key concepts and requirements that represent Part 2 of the ModSpec.

=== The ModSpec and the "Form" of a standard

NOTE: For OGC Standards, the assumption is that documents are in a commonly used
logical form (template). 

In informative sections, the use of the word "will" implies that something is an implication of a requirement. The "will" statements are not requirements but explain the consequence of requirements.

The ModSpec defines a "requirement" of a standard as an atomic testable
criterion. See the formal definition of requirement in <<term-requirement>>

[[cls-6-1]]
=== Optional Requirements class: UML model extension to the core

If the organizing mechanism for the data model used in the standard is an object model, then the
mapping from parts of the model to the requirements classes should follow the
logical mechanism described here.

The terminology used here is common to all versions of the UML standard, and may
be applied to any such version.

First, by the requirements above, the extension relationship of this conformance
test class to the core will be made explicit.

[cols="1,4",width="90%"]
|===
2+|*Requirements Class - UML extension to the core* 
2+|/req/core/data-representation 
|Target | ModSpec Conformant UML Model
|Dependency |OGC ModSpec Version 1.1 [OGC 25-003r1]
|REQ001 | /req/part2/uml/conformance-with-core 
|REQ002 | /req/part2/uml/object-model 
|REQ003 | /req/part2/uml/dependency-graph 
|REQ004 | /req/part2/uml/leaf-package
|REQ005 | /req/part2/uml/class-package
|REQ006 | /req/part2/uml/to-leaf
|REQ007 | /req/part2/uml/common-req-classes
|REQ008 | /req/part2/uml/source-target
|REQ009 | /req/part2/uml/leaf-package-dependency
|REQ010 | /req/part2/uml/two-way-dependency
|REQ011 | /req/part2/uml/segregate-into-leaf-packages
|===

Any conformant UML extension will comply with the ModSpec Core requirements class.

[[req-01]]
[requirement,model=ogc,type="general"]

[width="90%",cols="2,6"]
|===
|*REQ001* | */req/part2/uml/conformance-with-core* +
An implementation passing the UML conformance test class _SHALL_ first pass the ModSpec core
conformance test class
|===

Assuming all legitimate direct package dependencies are included in the UML model,
the conformance/requirements class associated to a package stem:[A] will directly
reference the conformance/requirements class associated to another package stem:[B],
if and only if stem:[A] is dependent on stem:[B]. Indirect dependencies will be
dealt with as the conformance classes cascade.

This clause uses UML terminology, but other object modeling languages and, if
needed, the object code itself can be mapped to a UML model. 

[[req-02]]
[requirement,model=ogc,type="general"]

[width="90%",cols="2,6"]
|===
|*REQ002* | */req/part2/uml/object-model* +
To be conformant to this UML requirements class, UML _SHALL_ be used to express the
object model, either as the core mechanism of the standard or as a normative adjunct
to formally explain the standard in a model
|===


[[req-03]]
[requirement,model=ogc,type="general"]
[width="90%",cols="2,6"]
|===
|*REQ003* | */req/part2/uml/dependency-graph* +
A UML model _SHALL_ have an explicit dependency graph for the leaf packages and
external packages used by the standard consistent with the way their classifiers use
those of other packages
|===

NOTE: External packages having predated the current version of the standard will
not normally have dependencies to packages within the standard.

Other dependencies (indirect) will arise from the transitive closure of the above
direct dependencies. That means if stem:[A] depends on stem:[B], and stem:[B]
depends on stem:[C] then stem:[A] depends on stem:[C]. Since these indirect
dependencies will show up in the cascade of included conformance tests based solely
on the direct dependencies, we can ignore them for effects on structure.

Since a package can consist solely of other packages, there is always the capability
to define in UML a single package that will correspond to a particular requirements
class and its associated conformance class.

[[req-04]]
[requirement,model=ogc,type="general"]
[width="90%",cols="2,6"]
|===
|*REQ004* | */req/part2/uml/leaf-model* +
A UML leaf package _SHALL_ be associated directly to only one requirements class.
|===

[[req-05]]
[requirement,model=ogc,type="general"]
[width="90%",cols="2,6"]
|===
|*REQ005* | */req/part2/uml/class-package* +
Each requirements class shall be associated to a unique package in the model and
include either directly or by a dependency any requirement associated to any of its
subpackages.
|===

The class definitions are the "requirements" of a UML expressed standard. Therefore, the
logical consequence of the above is to organize requirements classes based on leaf
packages.

[[req-06]]
[requirement,model=ogc,type="general"]
[width="90%",cols="2,6"]
|===
|*REQ006* | */req/part2/uml/to-leaf* +
A requirements class _SHALL_ be associated to some number of complete leaf packages
and all classes and constraints in those packages.
|===

If a requirement uses or refers to elements of more than one package, then one of
the packages will be called the source of the requirement, and the other targets.
The requirement with the same source package will always be associated with the same
requirements module and/or class.

[[req-07]]
[requirement,model=ogc,type="general"]
[width="90%",cols="2,6"]
|===
|*REQ007* | */req/part2/uml/common-req-classe* +
Classes that are common to all requirements classes _SHALL_ be in a package
associated to the core requirements class.
|===

This is actually a derived requirement and is repeated here for emphasis.

This dependency of requirements classes will be consistent with the usual mechanism
for describing the source and target of dependencies between packages. By Clause
<<req-22>> in the Core, only classes in the source requirements class will be affected by the
requirement.

In UML, source and target dependency relations are defined in such a way that the
source of the relation is dependent on the target of the relation.

[[req-08]]
[requirement,model=ogc,type="general"]
[width="90%",cols="2,6"]
|===
|*REQ008* | */req/part2/uml/source-target* +
^| A | In the UML model, if a "source" package is dependent on a "target" package then
their requirements class _SHALL_ be equal or 
^| B | The source package's class _SHALL_ be an extension of the target package's class.
|===

This means that the dependency graph of the UML packages parallels in some sense the
extension diagram of the requirements/conformance classes. If all leaf
packages of the model are moved into "requirements class packages" containing their
corresponding modeling packages the model then satisfies the following
recommendation: 

*#Each requirements class in a conformant standard should be
associated to one and only one UML package (which may contain sub-packages for a
finer level of structure). If the core requirements class contains only
recommendations, it may be an exception to this.#*

[[req-09]]
[requirement,model=ogc,type="general"]
[width="90%",cols="2,6"]
|===
|*REQ009* | */req/part2/uml/leaf-package-dependency* +
If one leaf package is dependent on another leaf package, then the requirements
class of the first _SHALL_ be the same or an extension of the requirements class of
the second.
|===

[[req-10]]
[requirement,model=ogc,type="general"]
[width="90%",cols="2,6"]
|===
|*REQ010* | */req/part2/uml/two-way-dependency* +
If two packages have a two-way dependency (a "co-dependency"), they _SHALL_ be
associated to the same requirements class.
|===

For example, if two classes have a two-way navigable association, then these two
classes must be (transitively) in the same conformance requirements class package.

The hierarchical structure of a UML model is based on UML classes, residing in UML
packages. UML packages can then reside in larger UML packages. Although there is
nothing to demand it, it is a common practice to move all classes down the hierarchy
to leaf packages. Leaf packages are those that contain only classes (that is,
contain no smaller subpackages). Classes can act as packages in the sense that a UML
class can contain a locally defined class whose scope is the class itself. For our
purposes, we will consider a class and its contained local classes to all be in the
package of the original class.

[[req-11]]
[requirement,model=ogc,type="general"]
[width="90%",cols="2,6"]
|===
|*REQ011* | */req/part2/uml/segregate-into-leaf-packages* +
The UML model _SHALL_ segregate all classes into leaf packages.
|===
